//@ts-ignore - this is generated by the build script
import { map } from "@/.map";
import { loader } from "fumadocs-core/source";
import { createMDXSource } from "fumadocs-mdx";

export const { getPage, getPages, pageTree } = loader({
	baseUrl: "/docs",
	rootDir: "docs",
	source: createMDXSource(map),
});
