name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup

      - name: Lint
        run: bun lint

      - name: Typecheck
        run: bun typecheck

      - name: Test
        run: bun test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["test"]
    if: ${{!contains(github.event.head_commit.message, 'skip-release') && !contains(github.event.head_commit.message, 'skip-ci') && github.event_name != 'pull_request' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup

      - name: Build
        run: bun run build

      - name: Create Release
        id: semantic
        run: bunx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
