name: CI
on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main
jobs:
  test:
    name: test, lint & typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup

      - name: Lint
        run: bun lint

      - name: Typecheck
        run: bun typecheck

      - name: Test
        run: bun run test
  release: 
    name: release
    needs: test
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'skip release') && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: ./.github/setup

      - name: Build
        run: bun run build

      - name: Publish to NPM
        run:  npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}